import fs from "fs-extra";
import path from "path";
import { execSync } from "child_process";
import { v4 as uuid } from "uuid";
import { logger } from "../utils/logger.js";

export interface ProjectConfig {
  projectId: string;
  projectName: string;
  template: "web-static" | "web-db-user" | "web-ai-agent" | "mobile-app";
  owner: {
    userId: string;
    email: string;
    name: string;
  };
  features: string[];
  environment: "development" | "staging" | "production";
}

export class TemplateGenerator {
  private templatesDir: string;
  private projectsDir: string;

  constructor(
    templatesDir: string = "/templates",
    projectsDir: string = "/projects"
  ) {
    this.templatesDir = templatesDir;
    this.projectsDir = projectsDir;
  }

  /**
   * Generate a new project from template
   */
  async generateProject(config: ProjectConfig): Promise<{
    projectPath: string;
    gitRepo: string;
    environmentVariables: Record<string, string>;
  }> {
    logger.info(`[TemplateGenerator] Generating project: ${config.projectName}`);

    // 1. Create project directory
    const projectPath = path.join(
      this.projectsDir,
      config.projectId,
      config.projectName
    );
    await fs.ensureDir(projectPath);
    logger.info(`[TemplateGenerator] Created directory: ${projectPath}`);

    // 2. Copy template files
    const templatePath = path.join(this.templatesDir, config.template);
    if (await fs.pathExists(templatePath)) {
      await this.copyTemplate(templatePath, projectPath, config);
    } else {
      logger.warn(`[TemplateGenerator] Template not found: ${templatePath}, creating minimal project`);
      await this.createMinimalProject(projectPath, config);
    }

    // 3. Initialize git repository
    const gitRepo = await this.initializeRepository(projectPath, config);

    // 4. Generate environment variables
    const environmentVariables = await this.generateEnvironment(config);

    // 5. Create .env.local file
    await this.createEnvFile(projectPath, environmentVariables);

    // 6. Install dependencies
    await this.installDependencies(projectPath);

    // 7. Create initial commit
    await this.createInitialCommit(projectPath, config);

    logger.info(`[TemplateGenerator] Project generated successfully at ${projectPath}`);

    return {
      projectPath,
      gitRepo,
      environmentVariables,
    };
  }

  /**
   * Copy template and customize for project
   */
  private async copyTemplate(
    templatePath: string,
    projectPath: string,
    config: ProjectConfig
  ): Promise<void> {
    logger.info(`[TemplateGenerator] Copying template from ${templatePath}`);

    await fs.copy(templatePath, projectPath, {
      filter: (src) => {
        return !src.includes("node_modules") && !src.includes(".git");
      },
    });

    // Customize package.json
    const packageJsonPath = path.join(projectPath, "package.json");
    if (await fs.pathExists(packageJsonPath)) {
      const packageJson = await fs.readJSON(packageJsonPath);
      packageJson.name = config.projectName;
      packageJson.version = "1.0.0";
      packageJson.description = `${config.projectName} - Generated by Agentic Platform`;
      packageJson.author = config.owner.name;
      await fs.writeJSON(packageJsonPath, packageJson, { spaces: 2 });
    }

    // Create README
    const readme = this.generateReadme(config);
    await fs.writeFile(path.join(projectPath, "README.md"), readme);
  }

  /**
   * Create minimal project structure
   */
  private async createMinimalProject(
    projectPath: string,
    config: ProjectConfig
  ): Promise<void> {
    logger.info(`[TemplateGenerator] Creating minimal project structure`);

    const packageJson = {
      name: config.projectName,
      version: "1.0.0",
      description: `${config.projectName} - Generated by Agentic Platform`,
      main: "index.js",
      type: "module",
      scripts: {
        dev: "node index.js",
        build: "echo 'Build script not configured'",
        start: "node index.js",
      },
      author: config.owner.name,
      license: "MIT",
    };

    await fs.writeJSON(path.join(projectPath, "package.json"), packageJson, {
      spaces: 2,
    });

    // Create basic index.js
    const indexJs = `console.log('${config.projectName} started');`;
    await fs.writeFile(path.join(projectPath, "index.js"), indexJs);

    // Create README
    const readme = this.generateReadme(config);
    await fs.writeFile(path.join(projectPath, "README.md"), readme);
  }

  /**
   * Initialize git repository
   */
  private async initializeRepository(
    projectPath: string,
    config: ProjectConfig
  ): Promise<string> {
    logger.info(`[TemplateGenerator] Initializing git repository`);

    try {
      execSync("git init", { cwd: projectPath });
      execSync(`git config user.email "${config.owner.email}"`, {
        cwd: projectPath,
      });
      execSync(`git config user.name "${config.owner.name}"`, {
        cwd: projectPath,
      });

      const gitignore = `
node_modules/
dist/
build/
.env
.env.local
.env.*.local
*.log
.DS_Store
.idea/
.vscode/
*.swp
*.swo
~*
.turbo/
.next/
out/
`;
      await fs.writeFile(path.join(projectPath, ".gitignore"), gitignore);

      return projectPath;
    } catch (error) {
      logger.error(`[TemplateGenerator] Git initialization failed`, { error });
      throw error;
    }
  }

  /**
   * Generate environment variables
   */
  private async generateEnvironment(config: ProjectConfig): Promise<Record<string, string>> {
    const env: Record<string, string> = {
      PROJECT_ID: config.projectId,
      PROJECT_NAME: config.projectName,
      ENVIRONMENT: config.environment,
      JWT_SECRET: this.generateSecret(64),
      API_KEY: this.generateSecret(32),
      ENABLE_AI_FEATURES: config.features.includes("ai") ? "true" : "false",
      ENABLE_DATABASE: config.features.includes("database") ? "true" : "false",
      ENABLE_STORAGE: config.features.includes("storage") ? "true" : "false",
      APP_URL: `https://${config.projectId}.agentic-platform.dev`,
      API_URL: `https://api-${config.projectId}.agentic-platform.dev`,
    };

    return env;
  }

  /**
   * Create .env.local file
   */
  private async createEnvFile(
    projectPath: string,
    env: Record<string, string>
  ): Promise<void> {
    const envContent = Object.entries(env)
      .map(([key, value]) => `${key}=${value}`)
      .join("\n");

    await fs.writeFile(path.join(projectPath, ".env.local"), envContent);
  }

  /**
   * Install dependencies
   */
  private async installDependencies(projectPath: string): Promise<void> {
    logger.info(`[TemplateGenerator] Installing dependencies`);

    try {
      const packageJsonPath = path.join(projectPath, "package.json");
      if (await fs.pathExists(packageJsonPath)) {
        execSync("npm install", { cwd: projectPath, stdio: "inherit" });
      }
    } catch (error) {
      logger.warn(`[TemplateGenerator] Dependency installation failed`, { error });
    }
  }

  /**
   * Create initial commit
   */
  private async createInitialCommit(
    projectPath: string,
    config: ProjectConfig
  ): Promise<void> {
    try {
      execSync("git add .", { cwd: projectPath });
      execSync(`git commit -m "Initial commit: ${config.projectName} project"`, {
        cwd: projectPath,
      });
      logger.info(`[TemplateGenerator] Initial commit created`);
    } catch (error) {
      logger.warn(`[TemplateGenerator] Initial commit failed`, { error });
    }
  }

  /**
   * Generate README
   */
  private generateReadme(config: ProjectConfig): string {
    return `# ${config.projectName}

Generated by Agentic Platform on ${new Date().toISOString()}

## Quick Start

\`\`\`bash
# Install dependencies
npm install

# Start development server
npm run dev

# Build for production
npm run build
\`\`\`

## Environment Variables

Copy \`.env.local\` and fill in your API keys:

- \`OPENAI_API_KEY\` - OpenAI API key
- \`ANTHROPIC_API_KEY\` - Anthropic API key
- \`DATABASE_URL\` - Database connection string

## Project Structure

\`\`\`
src/
├── server/     - Backend server
├── client/     - Frontend application
├── services/   - Business logic
└── utils/      - Utility functions
\`\`\`

## Documentation

- [Project Structure](./docs/structure.md)
- [API Reference](./docs/api.md)
- [Deployment Guide](./docs/deployment.md)

## Support

For issues and questions, visit: https://docs.agentic-platform.com
`;
  }

  /**
   * Generate secure random secret
   */
  private generateSecret(length: number): string {
    const chars =
      "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    let result = "";
    for (let i = 0; i < length; i++) {
      result += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return result;
  }
}
